os: Visual Studio 2015

version: 1.0.3.{build}

configuration:
- Release

platform:
- Any CPU
- x64
- x86

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- ps: Start-FileDownload 'https://download.microsoft.com/download/D/7/2/D725E47F-A4F1-4285-8935-A91AE2FCC06A/dotnet-sdk-2.0.3-win-gs-x64.exe'
- cmd: dotnet-sdk-2.0.3-win-gs-x64.exe /quiet
- ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- dotnet restore .\src\MediaInfo.DotNetWrapper\MediaInfo.DotNetWrapper.csproj
- dotnet build .\src\MediaInfo.DotNetWrapper\MediaInfo.DotNetWrapper.csproj -c %CONFIGURATION%

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'